version: '3'
services:
  client:
    build: ../client
    ports:
      - '3003:3001'
    env_file:
      - './docker.env'
    image: chnikel/item-manager-client

  server:
    build: ../server
    ports:
      - '3000:3000'
    volumes:
      - '../app/data:/data'
    env_file:
      - './docker.env'
    image: chnikel/item-manager-server
